### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [vismaymanoj/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - Commands, java files, and other code should be written with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command copies and runs the code on the remote server: Part 7 – Making Remote Running Even More Pleasant (this is from the lab in week 1) - Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by vismaymanoj** [comment]
I requested regrade. 
Thanks you.

**Comment by JIzabal** [comment]
Currently your commands, java files, and other code aren't written with backticks correctly. I see that you've used the backticks, but the syntax is a little off. To see how to do this please see the [Editing Markdown](https://ucsd-cse15l-w22.github.io/week/week2/#editing-markdown) section which provides links that can show you how to write code in Markdown with backticks.

For Step 6 of your lab report, your command currently copies, compiles, and runs everything locally (i.e., on your computer) instead of on the remote server (i.e., the computer you log into with `ssh`). We want you to copy the code from your computer to the remote server, compile the code that was copied onto the remote server, and then run the code that was compiled on the remote server. First, look into Part 5 of Lab 1 to see how to copy a file locally to the remote server using `scp`. Then, look into Part 7 of Lab 1 to see how to run commands (e.g., `javac` and `java`) on the remote server. There's an example of how to do this with `ls` but you need to do it for `javac` and `java`. Finally, see Part 7 of Lab 1 to figure out how to combine this all into one line through the use of semicolons. Let me know if you have any questions! Once you're done, go ahead and submit a regrade request.

**Comment by vismaymanoj** [comment]
Hello!
So sorry, I was going over my lab report 3 fixes and I realized I never did the backticks and running remotely properly. I thought I fixed it the first time but guess not. I have just done those. So sorry for the confusion.

**Comment by JIzabal** [comment]
No worries! The last step is still copying, compiling, and running locally. Read my above explanation on how to fix this so that you're copying the file to the remote server and then compiling and running the file there. If you have any questions feel free to ask! Once you've fixed this, comment on here and I'll fix your grade.

**Comment by vismaymanoj** [comment]
Hello! I believe I finally fixed it, thank you!

**Comment by JIzabal** [comment]
You're almost there! Consider replacing the `ls` with the `java` and `javac` commands so that you have something like `ssh your-account@ieng6.ucsd.edu "javac [file]; java [file]"`

**Comment by vismaymanoj** [comment]
Hello, I just did it. It says I cannot submit it on gradescope though, so I have attached my url down blow. Thank you so much!

https://vismaymanoj.github.io/cse15l-lab-reports/lab-report-1-week-2

**Comment by vismaymanoj** [comment]
Just finished!

**Comment by JIzabal** [comment]
Nice work!
